server:
  port: 8081

security:
  oauth2:
    resource:
      user-info-uri: https://api.github.com/user

spring:
  profile: dev
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
